org: pikimell
service: candy-store

frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  profile: serverlessUser
  timeout: 29

functions:
  getDistance:
    handler: src/handlers/googleMaps/getDistanceHandler.getDistanceHandler
    events:
      - http:
          path: distance
          method: post
          cors: true
